### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by KottV** [osxmidi/ScorchCrafter-JUCE#2]
Hi!

Found your addition about Automation in LV2Wrapper. Could you reveal this function? And is it safe to merge in LV2 tree?

**Comment by osxmidi** [comment]
> Hi!
> 
> Found your addition about Automation in LV2Wrapper. Could you reveal this function? And is it safe to merge in LV2 tree?

Hi.

I couldn't get Automation working with Juce 6 AudioProcessorValueTreeState and parameter listeners until I added that change in SetParameter (param->sendValueChangedMessageToListeners (value);)

I've been trying to get a Juce 6 LV2 Wrapper functioning as well (the LV2 zip file below) which you might want to look at, it seems to work so far for what I've been doing.

Feel free to use any of it if it is useful.

[LV2.zip](https://github.com/osxmidi/ScorchCrafter-JUCE/files/4945611/LV2.zip)

**Comment by KottV** [comment]
>>LV2.zip

holymoly! Thank You :)
